# GClaude Indexer — document collection indexer
# Copyright (C) 2026  Alex Camacho Castilho
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option)
# any later version. See the LICENSE file for details.

"""Package to set up a new Claude Project (explicit user request): bundles
the four already-generated artifacts (spec section 5, step 8) with a guide
explaining where to paste each one, into a single downloadable `.zip` —
even if the user is on a machine with no direct access to the output
folder.
"""

from __future__ import annotations

import io
import zipfile
from pathlib import Path

from .artifacts import INDEX_FILENAME, PROJECT_INSTRUCTIONS_FILENAME, REVIEW_FILENAME, TIMELINE_FILENAME
from .config import ProjectConfig

ARTIFACT_NAMES = (INDEX_FILENAME, TIMELINE_FILENAME, REVIEW_FILENAME, PROJECT_INSTRUCTIONS_FILENAME)

_GUIDE: dict[str, str] = {
    "pt": """\
# Como configurar este acervo num Claude Project novo

Este pacote tem os quatro arquivos gerados pelo GClaude Indexer para o
projeto "{name}", mais este guia.

## Passo a passo

1. Em claude.ai, crie um **Project** novo (ou abra um já existente para
   este acervo).
2. Abra `project_instructions.md` neste pacote e cole o conteúdo da seção
   **"Papel"** (a primeira, logo no topo do arquivo) no campo **"Project
   instructions"** do Project — é o que define como o Claude deve se
   comportar neste acervo, inclusive a regra de sempre confirmar valores
   no documento original antes de citar.
3. Em **"Project knowledge"** (arquivos do projeto), envie os quatro
   arquivos deste pacote: `index.md`, `timeline.md`, `review.md` e
   `project_instructions.md` — o Claude usa o índice e a cronologia para
   localizar a peça certa, e a conferência para saber o que ainda está
   pendente.
4. Mantenha a pasta de origem original (com os documentos-fonte)
   acessível separadamente — o índice e a cronologia servem para achar a
   peça, mas qualquer valor, data ou conteúdo de tabela citado numa
   resposta precisa ser confirmado no arquivo original, nunca só no
   índice (ele vem de OCR e classificação automática, que podem errar).

## Se o acervo crescer ou mudar

Gere os quatro arquivos de novo na tela "Resultado" do GClaude Indexer
("Importar e gerar relatórios") e reenvie-os para o mesmo Project,
substituindo os antigos.
""",
    "en": """\
# How to set up this collection in a new Claude Project

This package contains the four files generated by GClaude Indexer for
project "{name}", plus this guide.

## Step by step

1. In claude.ai, create a new **Project** (or open an existing one for
   this collection).
2. Open `project_instructions.md` in this package and paste the content of
   the **"Role"** section — the first one, right at the top of the file —
   into the Project's **"Project instructions"** field. This defines how
   Claude should behave for this collection, including the rule to always
   confirm values in the original document before citing them.
3. In **"Project knowledge"**, upload all four files in this package:
   `index.md`, `timeline.md`, `review.md` and
   `project_instructions.md` — Claude uses the index and the chronology to
   locate the right piece, and the coverage report to know what is still
   pending.
4. Keep the original source folder (with the source documents)
   accessible separately — the index and chronology are for locating a
   piece, but any value, date or table content cited in an answer must be
   confirmed in the original file, never from the index alone (it comes
   from OCR and automatic classification, both of which can be wrong).

## If the collection grows or changes

Regenerate the four files again on the "Result" screen of GClaude Indexer
("Import and generate reports") and re-upload them to the same Project,
replacing the old ones.
""",
    "es": """\
# Cómo configurar esta colección en un Claude Project nuevo

Este paquete tiene los cuatro archivos generados por GClaude Indexer para
el proyecto "{name}", más esta guía.

## Paso a paso

1. En claude.ai, cree un **Project** nuevo (o abra uno ya existente para
   esta colección).
2. Abra `project_instructions.md` en este paquete y pegue el contenido de
   la sección **"Rol"** — la primera, justo al inicio del archivo — en el
   campo **"Project instructions"** del Project: es lo que define cómo
   debe comportarse Claude en esta colección, incluida la regla de
   confirmar siempre los valores en el documento original antes de
   citarlos.
3. En **"Project knowledge"**, suba los cuatro archivos de este paquete:
   `index.md`, `timeline.md`, `review.md` e
   `project_instructions.md` — Claude usa el índice y la cronología para
   ubicar la pieza correcta, y el informe de cobertura para saber qué
   sigue pendiente.
4. Mantenga la carpeta de origen original (con los documentos fuente)
   accesible por separado — el índice y la cronología sirven para
   encontrar la pieza, pero cualquier valor, fecha o contenido de tabla
   citado en una respuesta debe confirmarse en el archivo original, nunca
   solo en el índice (viene de OCR y clasificación automática, que pueden
   fallar).

## Si la colección crece o cambia

Genere los cuatro archivos de nuevo en la pantalla "Resultado" de
GClaude Indexer ("Importar y generar informes") y vuelva a subirlos al
mismo Project, reemplazando los anteriores.
""",
}


# Fixed English name, like the four artifacts (Task 11): a file name that
# changed with the interface language would break any link or script that
# points at it, and the guide's own *content* is what carries the language.
GUIDE_FILENAME = "HOW_TO_USE.md"


def generate_claude_project_package(config: ProjectConfig, language: str) -> bytes:
    """Builds the `.zip` in memory — never writes anything to disk beyond
    what is already in `output_folder`, so no cleanup is needed afterwards."""
    output_folder = Path(config.output_folder)
    guide = _GUIDE.get(language, _GUIDE["pt"]).format(name=config.name)

    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as zip_file:
        zip_file.writestr(GUIDE_FILENAME, guide)
        for file_name in ARTIFACT_NAMES:
            path = output_folder / file_name
            if path.exists():
                zip_file.write(path, arcname=file_name)

    return buffer.getvalue()
